// Code generated by MockGen. DO NOT EDIT.
// Source: internal/billing/usecase/init.go
//
// Generated by this command:
//
//	mockgen -source=internal/billing/usecase/init.go -destination=_mock/billing/mock_usecase.go -package=mockbilling -mock_names=Billing=MockBillingUsecase
//

// Package mockbilling is a generated GoMock package.
package mockbilling

import (
	context "context"
	model "parkir-pintar/services/billing/internal/billing/model"
	apperror "parkir-pintar/services/billing/pkg/apperror"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBillingUsecase is a mock of Billing interface.
type MockBillingUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockBillingUsecaseMockRecorder
	isgomock struct{}
}

// MockBillingUsecaseMockRecorder is the mock recorder for MockBillingUsecase.
type MockBillingUsecaseMockRecorder struct {
	mock *MockBillingUsecase
}

// NewMockBillingUsecase creates a new mock instance.
func NewMockBillingUsecase(ctrl *gomock.Controller) *MockBillingUsecase {
	mock := &MockBillingUsecase{ctrl: ctrl}
	mock.recorder = &MockBillingUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingUsecase) EXPECT() *MockBillingUsecaseMockRecorder {
	return m.recorder
}

// CalculateAndCreateInvoice mocks base method.
func (m *MockBillingUsecase) CalculateAndCreateInvoice(ctx context.Context, req model.CreateInvoiceRequest) (*model.CreateInvoiceResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateAndCreateInvoice", ctx, req)
	ret0, _ := ret[0].(*model.CreateInvoiceResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CalculateAndCreateInvoice indicates an expected call of CalculateAndCreateInvoice.
func (mr *MockBillingUsecaseMockRecorder) CalculateAndCreateInvoice(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateAndCreateInvoice", reflect.TypeOf((*MockBillingUsecase)(nil).CalculateAndCreateInvoice), ctx, req)
}

// GetInvoice mocks base method.
func (m *MockBillingUsecase) GetInvoice(ctx context.Context, invoiceID string) (*model.GetInvoiceResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoice", ctx, invoiceID)
	ret0, _ := ret[0].(*model.GetInvoiceResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetInvoice indicates an expected call of GetInvoice.
func (mr *MockBillingUsecaseMockRecorder) GetInvoice(ctx, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoice", reflect.TypeOf((*MockBillingUsecase)(nil).GetInvoice), ctx, invoiceID)
}

// HandleParkingPaymentDone mocks base method.
func (m *MockBillingUsecase) HandleParkingPaymentDone(ctx context.Context, invoiceID, status string) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleParkingPaymentDone", ctx, invoiceID, status)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// HandleParkingPaymentDone indicates an expected call of HandleParkingPaymentDone.
func (mr *MockBillingUsecaseMockRecorder) HandleParkingPaymentDone(ctx, invoiceID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleParkingPaymentDone", reflect.TypeOf((*MockBillingUsecase)(nil).HandleParkingPaymentDone), ctx, invoiceID, status)
}

// RetryPayment mocks base method.
func (m *MockBillingUsecase) RetryPayment(ctx context.Context, req model.RetryPaymentRequest) (*model.RetryPaymentResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryPayment", ctx, req)
	ret0, _ := ret[0].(*model.RetryPaymentResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// RetryPayment indicates an expected call of RetryPayment.
func (mr *MockBillingUsecaseMockRecorder) RetryPayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryPayment", reflect.TypeOf((*MockBillingUsecase)(nil).RetryPayment), ctx, req)
}
