// Code generated by MockGen. DO NOT EDIT.
// Source: internal/billing/repository/init.go
//
// Generated by this command:
//
//	mockgen -source=internal/billing/repository/init.go -destination=_mock/billing/mock_repository.go -package=mockbilling -mock_names=Billing=MockBillingRepository
//

// Package mockbilling is a generated GoMock package.
package mockbilling

import (
	context "context"
	model "parkir-pintar/services/billing/internal/billing/model"
	apperror "parkir-pintar/services/billing/pkg/apperror"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDB) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockDBMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDB)(nil).Begin), ctx)
}

// Exec mocks base method.
func (m *MockDB) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDB)(nil).Exec), varargs...)
}

// QueryRow mocks base method.
func (m *MockDB) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockDBMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockDB)(nil).QueryRow), varargs...)
}

// MockBillingRepository is a mock of Billing interface.
type MockBillingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBillingRepositoryMockRecorder
	isgomock struct{}
}

// MockBillingRepositoryMockRecorder is the mock recorder for MockBillingRepository.
type MockBillingRepositoryMockRecorder struct {
	mock *MockBillingRepository
}

// NewMockBillingRepository creates a new mock instance.
func NewMockBillingRepository(ctrl *gomock.Controller) *MockBillingRepository {
	mock := &MockBillingRepository{ctrl: ctrl}
	mock.recorder = &MockBillingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingRepository) EXPECT() *MockBillingRepositoryMockRecorder {
	return m.recorder
}

// CreateInvoice mocks base method.
func (m *MockBillingRepository) CreateInvoice(ctx context.Context, invoice *model.Invoice) (*model.Invoice, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", ctx, invoice)
	ret0, _ := ret[0].(*model.Invoice)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockBillingRepositoryMockRecorder) CreateInvoice(ctx, invoice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockBillingRepository)(nil).CreateInvoice), ctx, invoice)
}

// GetByID mocks base method.
func (m *MockBillingRepository) GetByID(ctx context.Context, invoiceID string) (*model.Invoice, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, invoiceID)
	ret0, _ := ret[0].(*model.Invoice)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBillingRepositoryMockRecorder) GetByID(ctx, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBillingRepository)(nil).GetByID), ctx, invoiceID)
}

// GetByIDForDriver mocks base method.
func (m *MockBillingRepository) GetByIDForDriver(ctx context.Context, invoiceID, driverID string) (*model.Invoice, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDForDriver", ctx, invoiceID, driverID)
	ret0, _ := ret[0].(*model.Invoice)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetByIDForDriver indicates an expected call of GetByIDForDriver.
func (mr *MockBillingRepositoryMockRecorder) GetByIDForDriver(ctx, invoiceID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDForDriver", reflect.TypeOf((*MockBillingRepository)(nil).GetByIDForDriver), ctx, invoiceID, driverID)
}

// GetByIdempotencyKey mocks base method.
func (m *MockBillingRepository) GetByIdempotencyKey(ctx context.Context, key string) (*model.Invoice, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*model.Invoice)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetByIdempotencyKey indicates an expected call of GetByIdempotencyKey.
func (mr *MockBillingRepositoryMockRecorder) GetByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdempotencyKey", reflect.TypeOf((*MockBillingRepository)(nil).GetByIdempotencyKey), ctx, key)
}

// UpdateInvoiceStatus mocks base method.
func (m *MockBillingRepository) UpdateInvoiceStatus(ctx context.Context, invoiceID string, status model.InvoiceStatus) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInvoiceStatus", ctx, invoiceID, status)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// UpdateInvoiceStatus indicates an expected call of UpdateInvoiceStatus.
func (mr *MockBillingRepositoryMockRecorder) UpdateInvoiceStatus(ctx, invoiceID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInvoiceStatus", reflect.TypeOf((*MockBillingRepository)(nil).UpdateInvoiceStatus), ctx, invoiceID, status)
}

// UpdateStatusToPendingPayment mocks base method.
func (m *MockBillingRepository) UpdateStatusToPendingPayment(ctx context.Context, invoiceID string) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusToPendingPayment", ctx, invoiceID)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// UpdateStatusToPendingPayment indicates an expected call of UpdateStatusToPendingPayment.
func (mr *MockBillingRepositoryMockRecorder) UpdateStatusToPendingPayment(ctx, invoiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusToPendingPayment", reflect.TypeOf((*MockBillingRepository)(nil).UpdateStatusToPendingPayment), ctx, invoiceID)
}
